language: c

dist: trusty

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -qq g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 90

compiler:
  - clang
  - gcc

script:
  - cd src/ && make && make test
